invoicer:
    extends: 
        file: common.yml
        service: invoicer_base
    ports:
        - "8000:8000"
    volumes:
        - "./:/src"
    environment:
        DJANGO_SETTINGS_MODULE: invoicer.settings
        DEBUG: ${DEBUG}
        DATABASE_URL: ${DATABASE_URL}
        HIDE_DOCS: ${HIDE_DOCS}
